/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.User;
import model.UserList;

/**
 *
 * @author meghnahavalgi
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    UserList ulist;
    User user;
    public AdminJPanel(UserList ulist) {
        initComponents();
        this.ulist = ulist;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminSplitPane = new javax.swing.JSplitPane();
        adminContentArea = new javax.swing.JPanel();
        btnAddPerson = new javax.swing.JButton();
        btnListofPersons = new javax.swing.JButton();
        adminSubmenu = new javax.swing.JPanel();

        adminContentArea.setBackground(new java.awt.Color(204, 204, 255));

        btnAddPerson.setBackground(new java.awt.Color(255, 255, 204));
        btnAddPerson.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnAddPerson.setText("Add a new Person");
        btnAddPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        btnListofPersons.setBackground(new java.awt.Color(255, 255, 204));
        btnListofPersons.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnListofPersons.setText("List of Persons");
        btnListofPersons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnListofPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListofPersonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminContentAreaLayout = new javax.swing.GroupLayout(adminContentArea);
        adminContentArea.setLayout(adminContentAreaLayout);
        adminContentAreaLayout.setHorizontalGroup(
            adminContentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminContentAreaLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(adminContentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListofPersons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        adminContentAreaLayout.setVerticalGroup(
            adminContentAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminContentAreaLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(btnListofPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
        );

        adminSplitPane.setRightComponent(adminContentArea);

        adminSubmenu.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout adminSubmenuLayout = new javax.swing.GroupLayout(adminSubmenu);
        adminSubmenu.setLayout(adminSubmenuLayout);
        adminSubmenuLayout.setHorizontalGroup(
            adminSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        adminSubmenuLayout.setVerticalGroup(
            adminSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        adminSplitPane.setLeftComponent(adminSubmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminSplitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        RegisterJPanel registerPanel = new RegisterJPanel(ulist);
        adminSplitPane.setRightComponent(registerPanel);
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnListofPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListofPersonsActionPerformed
        // TODO add your handling code here:
        AdminViewJPanel adminview = new AdminViewJPanel(ulist);
        adminSplitPane.setRightComponent(adminview);
        
    }//GEN-LAST:event_btnListofPersonsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminContentArea;
    private javax.swing.JSplitPane adminSplitPane;
    private javax.swing.JPanel adminSubmenu;
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnListofPersons;
    // End of variables declaration//GEN-END:variables

}
