/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.User;
import model.UserList;

/**
 *
 * @author meghnahavalgi
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    UserList ulist;
    User user;
    
    public LoginJPanel(UserList ulist) {
        initComponents();
        this.ulist = ulist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginSplitPane = new javax.swing.JSplitPane();
        loginMenu = new javax.swing.JPanel();
        loginContent = new javax.swing.JPanel();
        txtLgpassword = new javax.swing.JPasswordField();
        cbLgshowpassword = new javax.swing.JCheckBox();
        lblLgpassword = new javax.swing.JLabel();
        lblLgusername = new javax.swing.JLabel();
        txtLgusername = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout loginMenuLayout = new javax.swing.GroupLayout(loginMenu);
        loginMenu.setLayout(loginMenuLayout);
        loginMenuLayout.setHorizontalGroup(
            loginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        loginMenuLayout.setVerticalGroup(
            loginMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        loginSplitPane.setLeftComponent(loginMenu);

        loginContent.setBackground(new java.awt.Color(204, 204, 255));

        cbLgshowpassword.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        cbLgshowpassword.setText("Show Password");
        cbLgshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLgshowpasswordActionPerformed(evt);
            }
        });

        lblLgpassword.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lblLgpassword.setText("PASSWORD:");

        lblLgusername.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        lblLgusername.setText("USERNAME:");

        lblLogin.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("PERSON LOGIN PAGE");

        btnlogin.setBackground(new java.awt.Color(255, 255, 204));
        btnlogin.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginContentLayout = new javax.swing.GroupLayout(loginContent);
        loginContent.setLayout(loginContentLayout);
        loginContentLayout.setHorizontalGroup(
            loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
            .addGroup(loginContentLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbLgshowpassword)
                    .addGroup(loginContentLayout.createSequentialGroup()
                        .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLgpassword)
                            .addComponent(lblLgusername))
                        .addGap(90, 90, 90)
                        .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLgusername, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtLgpassword)
                            .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginContentLayout.setVerticalGroup(
            loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContentLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLgusername)
                    .addComponent(txtLgusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(loginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLgpassword)
                    .addComponent(txtLgpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(cbLgshowpassword)
                .addGap(41, 41, 41)
                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        loginSplitPane.setRightComponent(loginContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbLgshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLgshowpasswordActionPerformed
        // TODO add your handling code here:

        if (cbLgshowpassword.isSelected()){
            txtLgpassword.setEchoChar((char)0);
        }
        else {
            txtLgpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_cbLgshowpasswordActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        String username = txtLgusername.getText();
        String password = txtLgpassword.getText();

        User authenticatedUser = authenticateUser(username, password);

        if(authenticatedUser != null){
            int userId = authenticatedUser.getId(); 
           

            UserViewJPanel userview = new UserViewJPanel(ulist,userId);
            loginSplitPane.setRightComponent(userview);

        }

    }//GEN-LAST:event_btnloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox cbLgshowpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLgpassword;
    private javax.swing.JLabel lblLgusername;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel loginContent;
    private javax.swing.JPanel loginMenu;
    private javax.swing.JSplitPane loginSplitPane;
    private javax.swing.JPasswordField txtLgpassword;
    private javax.swing.JTextField txtLgusername;
    // End of variables declaration//GEN-END:variables

     public User authenticateUser(String username, String password) {
         if (ulist == null) {
            throw new IllegalStateException("UserList is not properly initialized.");
        }
        ArrayList<User> users = ulist.getAllUsers();

        for (User user : users) {
            if (user.getUsername().equals(username)) {
                if (user.verifyPassword(password)) {
                    if (user.getStatus()) {
                        JOptionPane.showMessageDialog(this, "Login Successful");
                        return user; 
                    } else {
                        JOptionPane.showMessageDialog(this, "Account has been temporarily deactivated.");
                        return null; 
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Login failed. The password provided is not valid.");
                    return null; 
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Invalid username.");
        return null; 
    }
}
